name: johnnyboy
favicon: null
layout_spectrum: 0.97039
typography_spectrum: 0.8034252878278494
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.032354879193007946
  lightness: 0.33059525839053094
  saturation: 0.7277863780036569
  rhythmicContrast: 0.8746429407037795
purpose: []
